[bin] update

diff --git a/.local/bin/test-icpc b/.local/bin/test-icpc
--- a/.local/bin/test-icpc
+++ b/.local/bin/test-icpc
@@ -1,17 +1,25 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+YELLOW=$(tput setaf 3)
+NORMAL=$(tput sgr0)
+BOLD=$(tput bold)
+
 temp_file=$(mktemp)
 
 cleanup() {
 	if [[ -s "$temp_file" ]]; then
 		temp_dir=$(<"$temp_file")
-		echo -e "\n$temp_dir"
+		printf "\n%s" "$temp_dir"
 	fi
 	rm -f "$temp_file"
 	exit 0
 }
 
-create_temp_dir() {
+get_temp_dir() {
 	local temp=$(mktemp -d)
 	echo "$temp" >"$temp_file"
 	echo "$temp"
@@ -42,67 +50,80 @@ run_executable() {
 	local dir=$1
 	local executable=$2
 	for input_file in "$dir/in"*; do
+		local actual_output=$($executable <"$input_file")
 		local output_file="$dir/out${input_file##*in}"
-		if [ -f "$output_file" ]; then
-			local expected_output=$(<"$output_file")
-			local actual_output=$("$executable" <"$input_file")
-			local diff_output=$(colordiff -y --suppress-common-lines <(echo "$expected_output") <(echo "$actual_output"))
 
-			if [ -z "$diff_output" ]; then
-				echo "[PASS] $(basename "$input_file") and $(basename "$output_file")"
-			else
-				echo "[FAIL] $(basename "$input_file") and $(basename "$output_file"):"
-				echo "$diff_output"
-			fi
-		else
-			local actual_output=$("$executable" <"$input_file")
-			echo "[OUT] $(basename "$input_file")"
+		if [ ! -f "$output_file" ]; then
+			echo "${YELLOW}${BOLD}[OUT]${NORMAL} $(basename "$input_file")"
 			echo "$actual_output"
+			continue
+		fi
+
+		local diff_output=$(colordiff --suppress-common-lines <(echo "$actual_output") <(cat "$output_file"))
+
+		if [ -z "$diff_output" ]; then
+			echo "${GREEN}${BOLD}[PASS]${NORMAL} $(basename "$output_file")"
+		else
+			echo "${RED}${BOLD}[FAIL]${NORMAL} $(basename "$output_file"):"
+			echo "$diff_output"
 		fi
 
 	done
 }
 
 print_help() {
-	echo "Usage: $(basename "$0") [DIRECTORY] [EXECUTABLE]"
-	echo "DIRECTORY (optional): Specifies the directory containing the input and output files."
-	echo "EXECUTABLE (optional): Specifies the executable file to test against the input files."
-	echo "If no arguments are specified, a temporary directory will be created."
+	local script_name=$(basename "$0")
+	cat <<EOF
+Usage: $script_name [test_directory] [executable [arg ...]]
+
+    test_directory
+        Specifies the directory containing the inX and outX files.
+    
+    executable
+        Specifies the executable to test against the input files.
+  
+    If no arguments are specified, a temporary directory will be created.
+
+Examples:
+    $script_name                                    # add tests
+    $script_name /tmp/tmp.PdNZp0WaM2 python task.py # run tests
+    $script_name /tmp/tmp.PdNZp0WaM2                # add more tests
+EOF
 }
 
 main() {
-	if [[ $1 = -h || $1 = --help ]]; then
-		print_help
-		exit 0
-	elif [[ $# -eq 0 ]]; then
-		local temp_dir=$(create_temp_dir)
+	if [[ $# -eq 0 ]]; then
+		local temp_dir="$(get_temp_dir)"
 		local count=1
 		while true; do
-			get_data_pair $count "$temp_dir"
-			count=$((count + 1))
+			get_data_pair "$count" "$temp_dir"
+			count="$((count + 1))"
 		done
+	elif [[ $1 = -h || $1 = --help ]]; then
+		print_help
+		exit 0
 	elif [[ $# -eq 1 ]]; then
-		local dir="$(realpath "$1")"
-		if [ ! -d "$dir" ]; then
+		if [ ! -d "$1" ]; then
 			echo "Error: $dir is not a valid directory."
 			exit 1
 		fi
-		local count=$(watch_directory "$dir")
+
+		cd "$PWD" || exit 1
+		local dir="$1"
+		local count="$(watch_directory "$dir")"
 		while true; do
-			get_data_pair $count "$dir"
-			count=$((count + 1))
+			get_data_pair "$count" "$dir"
+			count="$((count + 1))"
 		done
-	elif [[ $# -eq 2 ]]; then
-		local dir="$(realpath "$1")"
-		if [ ! -d "$dir" ]; then
+	else
+		if [ ! -d "$1" ]; then
 			echo "Error: $dir is not a valid directory."
 			exit 1
 		fi
-		local executable="$(realpath "$2")"
-		if [ ! -x "$executable" ]; then
-			echo "Error: $executable is not an executable file."
-			exit 1
-		fi
+
+		cd "$PWD" || exit 1
+		local dir="$1" && shift 1
+		local executable="$*"
 		run_executable "$dir" "$executable"
 	fi
 }
diff --git a/.local/bin/tmux-session-dev b/.local/bin/tmux-session-dev
--- a/.local/bin/tmux-session-dev
+++ b/.local/bin/tmux-session-dev
@@ -1,36 +1,53 @@
 #!/usr/bin/env bash
 
-work_dir="${1:-$(mktemp -d ~/code/XXXX)}"
+work_dir="$PWD"
+session_name=""
 
-if ! test -d work_dir; then
+while [[ $# -gt 0 ]]; do
+	case "$1" in
+	-t)
+		session_name="$2"
+		shift 2
+		;;
+	*)
+		work_dir="$(realpath "$1")"
+		shift
+		;;
+	esac
+done
+
+if [ -z "$session_name" ]; then
+	session_name="$(basename "$work_dir")"
+fi
+
+if tmux has-session -t "$session_name" 2>/dev/null; then
+	echo "Error: Session '$session_name' already exists" >&2
+	exit 1
+fi
+
+if ! test -d "$work_dir"; then
 	mkdir -p "$work_dir"
 fi
 
-session_name="${2:-dev-$(basename "$work_dir")}"
+shell_name="$(basename "$SHELL")"
 
-tmux has-session -t "$session_name" 2>/dev/null
-
-if [ $? -ne 0 ]; then
-	shell_name="$(basename "$SHELL")"
-	
-	if command -v lvim &>/dev/null; then
-		EDITOR="lvim"
-	fi
-
-	filemanager="$SHELL"
-	if command -v lf &>/dev/null; then
-		filemanager="lf"
-	fi
-	
-	tmux new-session -d -c "$work_dir" -s "$session_name" -n "$shell_name"
-	tmux split-window -c "$work_dir" -t "$session_name":"$shell_name" -v
-	tmux split-window -c "$work_dir" -t "$session_name":"$shell_name".0 -h
-	tmux send-keys -t "$session_name":"$shell_name".2 "$filemanager" C-m
-	tmux select-pane -t "$session_name":"$shell_name".0
-
-	tmux new-window -c "$work_dir" -t "$session_name" -n "$EDITOR"
-	tmux split-window -bZ -t "$session_name":"$EDITOR" -v
-	tmux send-keys -t "$session_name":"$EDITOR".0 "$EDITOR" C-m
+if command -v lvim &>/dev/null; then
+	EDITOR="lvim"
 fi
+
+filemanager="$SHELL"
+if command -v lf &>/dev/null; then
+	filemanager="lf"
+fi
+
+tmux new-session -d -c "$work_dir" -s "$session_name" -n "$shell_name"
+tmux split-window -v -c "$work_dir" -t "$session_name":"$shell_name"
+tmux split-window -h -c "$work_dir" -t "$session_name":"$shell_name".0
+tmux send-keys -t "$session_name":"$shell_name".2 "$filemanager" C-m
+tmux select-pane -t "$session_name":"$shell_name".0
+
+tmux new-window -c "$work_dir" -t "$session_name" -n "$EDITOR"
+tmux split-window -bvZ -c "$work_dir" -t "$session_name":"$EDITOR"
+tmux send-keys -t "$session_name":"$EDITOR".0 "$EDITOR" C-m
 
 tmux attach-session -t "$session_name"
